# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /frontend

# Copy package.json and package-lock.json
COPY package*.json ./

RUN npm install --omit=dev

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
