FROM node:20-alpine

WORKDIR /frontend

COPY package.json .
COPY package-lock.json .

RUN npm install 

COPY . .

EXPOSE 3000

CMD [ "npm","run","dev" ]

#docker build -f Dockerfile.dev -t your-image-name .